### ISSUE TITLE
Click on link in headless mode only works if directly called on page, but not on element

### ISSUE THREAD

**Issue by rammpeter** [YusukeIwaki/playwright-ruby-client#206]
### Step To Reproduce / Observed behavior

Calling click on a Playwright::ElementHandle selected by query_selector in headless Chromium mode leads to:

> Playwright::Error: Error: Element is not attached to the DOM
> attempting click action
>   waiting for element to be visible, enabled and stable
> 

In non-headless mode that works.
In contrast using `page.click(<selector>)` directly works also in headless mode.

Example:
Does not work in headless mode:
`page.query_selector('.slick-cell.l0.r0 a:visible').click`
Does work in headless mode:
`page.click('.slick-cell.l0.r0 a:visible')`

Initialization of playwright is done this way:
```
playwright = Playwright.create(playwright_cli_executable_path: 'npx playwright')
browser  = playwright.playwright.chromium.launch(headless: true)
page = browser.new_page(viewport: { width: 800, height: 500 })
page.set_default_timeout(60000)
page.goto("http://#{host}:#{port}")
```

### Expected behavior
Method click should also work in headless mode if called on elements

### Environment
jruby 9.3.3.0 (2.6.8) 2022-01-19 b26de1f5c5 OpenJDK 64-Bit Server VM 17.0.2+0 on 17.0.2+0 +jit [darwin-x86_64]

**Comment by YusukeIwaki** [comment]
@rammpeter I think the element  '.slick-cell.l0.r0 a:visible' is not clickable when `query_selector` is called.
`page.query_selector` does NOT auto-wait the element until it is clickable while `page.click` does auto-wait.
https://playwright.dev/docs/actionability

The simplest solution is replacing `query_selector` with `locator`. Note that page.locator returns `Locator` object instead of ElementHandle.
Another solution is using `wait_for_selector(sel, attached: true)` instead of `query_selector`. You can still use ElementHandle with this solution.

**Comment by rammpeter** [comment]
@YusukeIwaki Thank you very much for your explanations and please apologise my poor experience with playwright until now
